version: '3'
services:
  web:
    build: ./web server
    ports:
        - "5000:5000"
    links:
        - mongodb
    environment:
        - PORT=5000
        - ENV=production
        - MONGODB_HOST=mongodb
        - MONGODB_PORT=27017
  mongodb:
    image: mongo:3.4.9
    ports:
      - "21017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet